laravel/app/routes.php
<?php
Route::get('/', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::get('home', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::get('perfil/{slug?}', array('as' => 'perfil', 'uses' => 'PerfilController@index'));
Route::get('projetos/{categoria?}', array('as' => 'projetos', 'uses' => 'ProjetosController@index'));
Route::get('projetos/{categoria?}/{projeto?}', array('as' => 'projetos.detalhes', 'uses' => 'ProjetosController@detalhes'));
Route::get('contato', array('as' => 'contato', 'uses' => 'ContatoController@index'));
Route::post('enviarContato', array('as' => 'contato.envio', 'uses' => 'ContatoController@enviar'));

Route::get('painel', array('before' => 'auth', 'as' => 'painel.home', 'uses' => 'Painel\HomeController@index'));
Route::get('painel/login', array('as' => 'painel.login', 'uses' => 'Painel\HomeController@login'));

// Autenticação do Login
Route::post('painel/login',  array('as' => 'painel.auth', function(){
	$authvars = array(
		'username' => Input::get('username'),
		'password' => Input::get('password')
	);

	$lembrar = (Input::get('lembrar') == '1') ? true : false;

	if(Auth::attempt($authvars, $lembrar)){
		return Redirect::to('painel');
	}else{
		Session::flash('login_errors', true);
		return Redirect::to('painel/login');
	}
}));

Route::get('painel/logout', array('as' => 'painel.off', function(){
	Auth::logout();
	return Redirect::to('painel');
}));

Route::post('ajax/gravaOrdem', array('before' => 'auth', 'uses' => 'Painel\AjaxController@gravaOrdem'));

Route::group(array('prefix' => 'painel', 'before' => 'auth'), function()
{
	Route::any('multi-upload', 'Painel\AjaxController@upload');
    Route::resource('usuarios', 'Painel\UsuariosController');
    Route::resource('banners', 'Painel\BannersController');
	Route::resource('contato', 'Painel\ContatoController');
	Route::resource('projetos', 'Painel\ProjetosController');
	Route::resource('projetoimagens', 'Painel\ProjetoImagensController');
	Route::resource('frases', 'Painel\FrasesController');
	Route::resource('contatosrecebidos', 'Painel\ContatosEnviadosController');
	Route::resource('equipe', 'Painel\EquipeController');
	Route::resource('perfil', 'Painel\PerfilController');
//NOVASROTASDOPAINEL//
});

laravel/app/models/Perfil.php
<?php

class Perfil extends Eloquent
{

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'perfil';

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = array();

	// array of attributes we CAN set on the backend
    protected $fillable = array('', 'created_at', 'updated_at');

    // and those we CAN'T set on the backend
    protected $guarded = array('id');

}

laravel/app/controllers/PerfilController.php
<?php

use \Perfil, \Frase;

class PerfilController extends BaseController {

	protected $layout = 'frontend.templates.index';

	public function index($slug = 'a_arquiteta')
	{
		if($slug == 'equipe'){
			$texto = new Perfil;
			$texto->titulo = "EQUIPE";
			$texto->texto = "<p>EM BREVE</p>";
			$texto->imagem = "201429102014_equipe.jpg";
		}else{			
			$texto = Perfil::where('slug', '=', $slug)->first();
			if(!$texto) App::abort('404');
		}
			
		$frase = Frase::slug('perfil');
		$this->layout->content = View::make('frontend.perfil.index')->with('texto', $texto)
																	->with(compact('frase'))
																	->with('slugAtiva', $slug);
		
	}

}

laravel/app/controllers/painel/PerfilController.php
<?php

namespace Painel;

use \View, \Input, \Str, \Session, \Redirect, \Hash, \Thumb, \Tools, \File, Perfil;

class PerfilController extends BaseAdminController {

	protected $layout = 'backend.templates.index';

	public $limiteInsercao = '2';

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$this->layout->content = View::make('backend.perfil.index')->with('registros', Perfil::all())
																	->with('limiteInsercao', $this->limiteInsercao);		
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return Redirect::route('painel.perfil.index');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		return Redirect::route('painel.perfil.index');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$this->layout->content = View::make('backend.perfil.edit')->with('registro', Perfil::find($id));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$object = Perfil::find($id);

		$object->titulo = Input::get('titulo');
		$object->texto = Input::get('texto');
		$imagem = Thumb::make('imagem', 500, null, 'perfil/');
		if($imagem) $object->imagem = $imagem;

		$remover = Input::get('remover_imagem');
		if($remover == "1") $object->imagem = '';

		$imagem2 = Thumb::make('imagem2', 500, null, 'perfil/');
		if($imagem2) $object->imagem2 = $imagem2;

		$remover2 = Input::get('remover_imagem2');
		if($remover2 == "1") $object->imagem2 = '';

		try {

			$object->save();
			Session::flash('sucesso', true);
			Session::flash('mensagem', 'Texto alterado com sucesso.');
			return Redirect::route('painel.perfil.index');

		} catch (\Exception $e) {

			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(array('Erro ao criar Texto!'));

		}
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		return Redirect::route('painel.perfil.index');
	}

}

laravel/app/views/backend/perfil/edit.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Editar Texto
        </h2>  

		{{ Form::open( array('route' => array('painel.perfil.update', $registro->id), 'files' => true, 'method' => 'put') ) }}
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif	


				<div class="form-group">
					<label for="inputTítulo">Título</label>
					<input type="text" class="form-control" id="inputTítulo" name="titulo" value="{{$registro->titulo}}" required>
				</div>
				
				<div class="form-group">
					<label for="inputTexto">Texto</label>
					<textarea name="texto" class="form-control ckePerfil" id="inputTexto" >{{$registro->texto }}</textarea>
				</div>
				
				<div class="well">
					<label>Imagem 1</label><hr>

					<div class="form-group">
						@if($registro->imagem)
							Imagem 1 Atual<br>
							<img src="assets/images/perfil/{{$registro->imagem}}"><hr>
							<label for="inputImagem">Trocar Imagem 1</label>
							<input type="file" class="form-control" id="inputImagem" name="imagem">
							<hr>
							<label><input type="checkbox" value="1" name="remover_imagem"> Excluir Imagem</label>
						@else
							<label for="inputImagem">Adicionar Imagem 1</label>
							<input type="file" class="form-control" id="inputImagem" name="imagem">
						@endif
					</div>
				</div>

				<div class="well">
					<label>Imagem 2</label><hr>

					<div class="form-group">
						@if($registro->imagem2)
							Imagem 2 Atual<br>
							<img src="assets/images/perfil/{{$registro->imagem2}}"><hr>
							<label for="inputImagem">Trocar Imagem 2</label>
							<input type="file" class="form-control" id="inputImagem" name="imagem2">
							<hr>
							<label><input type="checkbox" value="1" name="remover_imagem2"> Excluir Imagem</label>
						@else
							<label for="inputImagem">Adicionar Imagem 2</label>
							<input type="file" class="form-control" id="inputImagem" name="imagem2">
						@endif
					</div>
				</div>
					

				<button type="submit" title="Alterar" class="btn btn-success">Alterar</button>

				<a href="{{URL::route('painel.perfil.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>
    
@stop

laravel/app/views/backend/perfil/form.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Adicionar Texto
        </h2>  

		<form action="{{URL::route('painel.perfil.store')}}" method="post" enctype="multipart/form-data">
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif


				<div class="form-group">
					<label for="inputTítulo">Título</label>
					<input type="text" class="form-control" id="inputTítulo" name="titulo" @if(Session::has('formulario')) value="{{ $s=Session::get('formulario'); echo $s['titulo'] }}" @endif required>
				</div>
				
				<div class="form-group">
					<label for="inputTexto">Texto</label>
					<textarea name="texto" class="form-control ckePerfil" id="inputTexto" >@if(Session::has('formulario')) {{ $s=Session::get('formulario'); echo $s['texto'] }} @endif</textarea>
				</div>
				
				<div class="form-group">
					<label for="inputImagem">Imagem</label>
					<input type="file" class="form-control" id="inputImagem" name="imagem" >
				</div>
				

				<button type="submit" title="Inserir" class="btn btn-success">Inserir</button>

				<a href="{{URL::route('painel.perfil.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>
    
@stop

laravel/app/views/backend/perfil/index.blade.php
@section('conteudo')

<div class="container">

    @if(Session::has('sucesso'))
        <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
    @endif

    @if($errors->any())
        <div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
    @endif

    <h2>
        Perfil @if(sizeof(Perfil::all()) < $limiteInsercao) <a href='{{ URL::route('painel.perfil.create') }}' class='btn btn-success btn-sm pull-right'><span class='glyphicon glyphicon-plus-sign'></span> Adicionar Texto</a> @endif
    </h2>

    <table class='table table-striped table-bordered table-hover'>

        <thead>
            <tr>
            	<th>Área do Site</th>
                <th>Título</th>
				<th>Texto</th>
				<th>Imagem</th>
                <th><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($registros as $registro)

            <tr class="tr-row" id="row_{{ $registro->id }}">
            	<td>
            		@if($registro->slug == 'a_arquiteta')
            			Perfil - A Arquiteta
            		@elseif($registro->slug == 'parcerias')
            			Perfil - Parcerias
            		@endif
            	</td>
                <td>{{ $registro->titulo }}</td>
				<td>{{ Str::words(strip_tags($registro->texto), 15) }}</td>
				<td><img src='assets/images/perfil/{{ $registro->imagem }}' style='max-width:150px'></td>
                <td class="crud-actions">
                    <a href='{{ URL::route('painel.perfil.edit', $registro->id ) }}' class='btn btn-primary btn-sm'>editar</a>						
                </td>
            </tr>

        @endforeach
        </tbody>

    </table>

    
</div>

@stop