laravel/app/routes.php
<?php
Route::get('/', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::get('home', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::get('perfil/{slug?}', array('as' => 'perfil', 'uses' => 'PerfilController@index'));
Route::get('projetos/{categoria?}', array('as' => 'projetos', 'uses' => 'ProjetosController@index'));
Route::get('projetos/{categoria?}/{projeto?}', array('as' => 'projetos.detalhes', 'uses' => 'ProjetosController@detalhes'));
Route::get('contato', array('as' => 'contato', 'uses' => 'ContatoController@index'));
Route::post('enviarContato', array('as' => 'contato.envio', 'uses' => 'ContatoController@enviar'));

Route::get('painel', array('before' => 'auth', 'as' => 'painel.home', 'uses' => 'Painel\HomeController@index'));
Route::get('painel/login', array('as' => 'painel.login', 'uses' => 'Painel\HomeController@login'));

// Autenticação do Login
Route::post('painel/login',  array('as' => 'painel.auth', function(){
	$authvars = array(
		'username' => Input::get('username'),
		'password' => Input::get('password')
	);

	$lembrar = (Input::get('lembrar') == '1') ? true : false;

	if(Auth::attempt($authvars, $lembrar)){
		return Redirect::to('painel');
	}else{
		Session::flash('login_errors', true);
		return Redirect::to('painel/login');
	}
}));

Route::get('painel/logout', array('as' => 'painel.off', function(){
	Auth::logout();
	return Redirect::to('painel');
}));

Route::post('ajax/gravaOrdem', array('before' => 'auth', 'uses' => 'Painel\AjaxController@gravaOrdem'));

Route::group(array('prefix' => 'painel', 'before' => 'auth'), function()
{
	Route::any('multi-upload', 'Painel\AjaxController@upload');
    Route::resource('usuarios', 'Painel\UsuariosController');
    Route::resource('banners', 'Painel\BannersController');
	Route::resource('contato', 'Painel\ContatoController');
	Route::resource('projetos', 'Painel\ProjetosController');
	Route::resource('projetoimagens', 'Painel\ProjetoImagensController');
	Route::resource('frases', 'Painel\FrasesController');
	Route::resource('contatosrecebidos', 'Painel\ContatosEnviadosController');
	Route::resource('equipe', 'Painel\EquipeController');
	Route::resource('perfil', 'Painel\PerfilController');
//NOVASROTASDOPAINEL//
});

laravel/app/controllers/painel/FrasesController.php
<?php

namespace Painel;

use \View, \Input, \Str, \Session, \Redirect, \Hash, \Thumb, \Tools, \File, Frase;

class FrasesController extends BaseAdminController {

	protected $layout = 'backend.templates.index';

	public $limiteInsercao = '3';

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$this->layout->content = View::make('backend.frases.index')->with('registros', Frase::all())->with('limiteInsercao', $this->limiteInsercao);
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$this->layout->content = View::make('backend.frases.form');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$object = new Frase;

		$object->frase = Input::get('frase');


		if($this->limiteInsercao && sizeof( Frase::all() ) >= $this->limiteInsercao)
			return Redirect::back()->withErrors(array('Número máximo de Registros atingido!'));

		
		try {

			$object->save();

			Session::flash('sucesso', true);
			Session::flash('mensagem', 'Frase criado com sucesso.');
			return Redirect::route('painel.frases.index');

		} catch (\Exception $e) {

			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(array('Erro ao criar Frase!'));	

		}
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$this->layout->content = View::make('backend.frases.edit')->with('registro', Frase::find($id));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$object = Frase::find($id);

		$object->frase = Input::get('frase');


		try {

			$object->save();
			Session::flash('sucesso', true);
			Session::flash('mensagem', 'Frase alterado com sucesso.');
			return Redirect::route('painel.frases.index');

		} catch (\Exception $e) {

			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(array('Erro ao criar Frase!'));

		}
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$object = Frase::find($id);
		$object->delete();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Frase removido com sucesso.');

		return Redirect::route('painel.frases.index');
	}

}

laravel/app/views/backend/frases/edit.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Editar Frase
        </h2>  

		{{ Form::open( array('route' => array('painel.frases.update', $registro->id), 'files' => true, 'method' => 'put') ) }}
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif

		    	<div class="form-group">
					<label for="inputTítulo">Título da Seção</label>
					<input type="text" class="form-control" disabled value="{{$registro->titulo}}">
				</div>

				<div class="form-group">
					<label for="inputFrase">Frase</label>
					<input type="text" class="form-control" id="inputFrase" name="frase" value="{{$registro->frase}}" required>
				</div>

				<button type="submit" title="Alterar" class="btn btn-success">Alterar</button>

				<a href="{{URL::route('painel.frases.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>
    
@stop

laravel/app/views/backend/frases/form.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Adicionar Frase
        </h2>  

		<form action="{{URL::route('painel.frases.store')}}" method="post" enctype="multipart/form-data">
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif


				<div class="form-group">
					<label for="inputFrase">Frase</label>
					<input type="text" class="form-control" id="inputFrase" name="frase" @if(Session::has('formulario')) value="{{ $s=Session::get('formulario'); echo $s['frase'] }}" @endif required>
				</div>
				

				<button type="submit" title="Inserir" class="btn btn-success">Inserir</button>

				<a href="{{URL::route('painel.frases.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>
    
@stop

laravel/app/views/backend/frases/index.blade.php
@section('conteudo')

<div class="container">

    @if(Session::has('sucesso'))
        <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
    @endif

    @if($errors->any())
        <div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
    @endif

    <h2>
        Frases @if(sizeof(Frase::all()) < $limiteInsercao) <a href='{{ URL::route('painel.frases.create') }}' class='btn btn-success btn-sm pull-right'><span class='glyphicon glyphicon-plus-sign'></span> Adicionar Frase</a> @endif
    </h2>

    <table class='table table-striped table-bordered table-hover'>

        <thead>
            <tr>
            	<th>Área</th>
            	<th>Frase</th>
                <th><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($registros as $registro)

            <tr class="tr-row" id="row_{{ $registro->id }}">
            	<td>{{$registro->titulo}}</td>
                <td>{{ $registro->frase }}</td>
                <td class="crud-actions">
                    <a href='{{ URL::route('painel.frases.edit', $registro->id ) }}' class='btn btn-primary btn-sm'>editar</a>
                </td>
            </tr>

        @endforeach
        </tbody>

    </table>

    
</div>

@stop