laravel/app/routes.php
<?php
Route::get('/', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::get('home', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::get('perfil/{slug?}', array('as' => 'perfil', 'uses' => 'PerfilController@index'));
Route::get('projetos/{categoria?}', array('as' => 'projetos', 'uses' => 'ProjetosController@index'));
Route::get('projetos/{categoria?}/{projeto?}', array('as' => 'projetos.detalhes', 'uses' => 'ProjetosController@detalhes'));
Route::get('contato', array('as' => 'contato', 'uses' => 'ContatoController@index'));
Route::post('enviarContato', array('as' => 'contato.envio', 'uses' => 'ContatoController@enviar'));

Route::get('painel', array('before' => 'auth', 'as' => 'painel.home', 'uses' => 'Painel\HomeController@index'));
Route::get('painel/login', array('as' => 'painel.login', 'uses' => 'Painel\HomeController@login'));

// Autenticação do Login
Route::post('painel/login',  array('as' => 'painel.auth', function(){
	$authvars = array(
		'username' => Input::get('username'),
		'password' => Input::get('password')
	);

	$lembrar = (Input::get('lembrar') == '1') ? true : false;

	if(Auth::attempt($authvars, $lembrar)){
		return Redirect::to('painel');
	}else{
		Session::flash('login_errors', true);
		return Redirect::to('painel/login');
	}
}));

Route::get('painel/logout', array('as' => 'painel.off', function(){
	Auth::logout();
	return Redirect::to('painel');
}));

Route::post('ajax/gravaOrdem', array('before' => 'auth', 'uses' => 'Painel\AjaxController@gravaOrdem'));

Route::group(array('prefix' => 'painel', 'before' => 'auth'), function()
{
	Route::any('multi-upload', 'Painel\AjaxController@upload');
    Route::resource('usuarios', 'Painel\UsuariosController');
    Route::resource('banners', 'Painel\BannersController');
	Route::resource('contato', 'Painel\ContatoController');
	Route::resource('projetos', 'Painel\ProjetosController');
	Route::resource('projetoimagens', 'Painel\ProjetoImagensController');
	Route::resource('frases', 'Painel\FrasesController');
	Route::resource('contatosrecebidos', 'Painel\ContatosEnviadosController');
	Route::resource('equipe', 'Painel\EquipeController');
	Route::resource('perfil', 'Painel\PerfilController');
//NOVASROTASDOPAINEL//
});

laravel/app/controllers/ProjetosController.php
<?php

use \PortfolioCategorias, \PortfolioProjetos, \PortfolioImagens;

class ProjetosController extends BaseController {

	protected $layout = 'frontend.templates.index';

	public function index($categoria_slug = 'todos')
	{
		$frase = Frase::slug('projetos');
		$lista_categorias = PortfolioCategorias::all();

		if($categoria_slug != 'todos'){

			$categoria = PortfolioCategorias::slug($categoria_slug);

			if(!$categoria) App::abort('404');

			$projetos = $categoria->projetos;

		}else{
			$projetos = PortfolioProjetos::ordenado();
		}

		$this->layout->content = View::make('frontend.projetos.index')->with(compact('frase'))
																	  ->with(compact('categoria_slug'))
																	  ->with(compact('projetos'))
																	  ->with(compact('lista_categorias'));
	}

	public function detalhes($categoria_slug = 'todos', $projeto_slug = '')
	{
		$frase = Frase::slug('projetos');
		$lista_categorias = PortfolioCategorias::all();

		$projeto = PortfolioProjetos::slug($projeto_slug);

		if(!$projeto) App::abort('404');
		
		$proximo = PortfolioProjetos::where('portfolio_categorias_id', '=', $projeto->portfolio_categorias_id)
									  	->where('ordem', '>', $projeto->ordem)
									  	->orderBy('ordem', 'asc')
									  	->first();

		$anterior = PortfolioProjetos::where('portfolio_categorias_id', '=', $projeto->portfolio_categorias_id)
									 	->where('ordem', '<', $projeto->ordem)
									 	->orderBy('ordem', 'desc')
									 	->first();
		
		$this->layout->content = View::make('frontend.projetos.detalhes')->with(compact('frase'))
																		 ->with(compact('categoria_slug'))
																	  	 ->with(compact('projeto'))
																	  	 ->with(compact('lista_categorias'))
																	  	 ->with(compact('proximo'))
																	  	 ->with(compact('anterior'));
	}
}

laravel/app/controllers/painel/ProjetosController.php
<?php

namespace Painel;

use \View, \Input, \Str, \Session, \Redirect, \Hash, \Thumb, \Tools, \File, PortfolioProjetos;

class ProjetosController extends BaseAdminController {

	protected $layout = 'backend.templates.index';

	protected $limiteInsercao = false;

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$projetos = PortfolioProjetos::where('portfolio_categorias_id', '=', Input::get('categoria'))->orderBy('ordem', 'ASC')->get();
		$this->layout->content = View::make('backend.projetos.index')->with('registros', $projetos)
																	 ->with('filtro', Input::get('categoria'))
																	 ->with('categorias', \PortfolioCategorias::all());
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$this->layout->content = View::make('backend.projetos.form')->with('categorias', \PortfolioCategorias::all())
																	->with('filtro', Input::get('categoria'));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$object = new PortfolioProjetos;

		$object->portfolio_categorias_id = Input::get('portfolio_categorias_id');
		$object->titulo = Input::get('titulo');
		$object->texto = Input::get('texto');
		
		$capa = Thumb::make('capa', 230, 230, 'projetos/capas/');
		if($capa) $object->capa = $capa;

		$object->ordem = Tools::defineOrdemProjeto($object->portfolio_categorias_id);
		
		try {

			$object->save();

			$object->slug = Tools::defineSlug(Input::get('titulo'), $object->id, 'portfolio_projetos');
			$object->save();

			Session::flash('sucesso', true);
			Session::flash('mensagem', 'Projeto criado com sucesso.');
			return Redirect::route('painel.projetos.index', array('categoria' => $object->portfolio_categorias_id));

		} catch (\Exception $e) {

			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(array('Erro ao criar Projeto!'));	

		}
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$this->layout->content = View::make('backend.projetos.edit')->with('registro', PortfolioProjetos::find($id))
																	->with('categorias', \PortfolioCategorias::all());
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$object = PortfolioProjetos::find($id);

		$object->portfolio_categorias_id = Input::get('portfolio_categorias_id');
		$object->titulo = Input::get('titulo');
		$object->texto = Input::get('texto');

		$capa = Thumb::make('capa', 230, 230, 'projetos/capas/');
		if($capa) $object->capa = $capa;

		$object->slug = Tools::defineSlug(Input::get('titulo'), $id, 'portfolio_projetos');
		
		try {

			$object->save();
			Session::flash('sucesso', true);
			Session::flash('mensagem', 'Projeto alterado com sucesso.');
			return Redirect::route('painel.projetos.index', array('categoria' => $object->portfolio_categorias_id));

		} catch (\Exception $e) {

			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(array('Erro ao criar Projeto!'));

		}
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$object = PortfolioProjetos::find($id);
		$redirectId = $object->portfolio_categorias_id;
		$object->delete();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Projeto removido com sucesso.');

		return Redirect::route('painel.projetos.index', array('categoria' => $redirectId));
	}

}

laravel/app/views/backend/projetos/edit.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Editar Projeto
        </h2>  

		{{ Form::open( array('route' => array('painel.projetos.update', $registro->id), 'files' => true, 'method' => 'put') ) }}
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif	


				<div class="form-group">
					<label for="inputCategoria">Categoria</label>					 
					<select	name="portfolio_categorias_id" class="form-control" id="inputCategoria" required>
						<option value="">Selecione</option>
						@if(sizeof($categorias))
							@foreach($categorias as $cat)
								<option value="{{$cat->id}}" @if($cat->id == $registro->portfolio_categorias_id) selected @endif>{{$cat->titulo}}</option>
							@endforeach
						@endif
					</select>
				</div>

				<div class="form-group">
					@if($registro->capa)
						Capa Atual<br>
						<img src="assets/images/projetos/capas/{{$registro->capa}}" style="max-width:400px;"><br>
					@endif
					<label for="inputImagem">Trocar Imagem de Capa</label>
					<input type="file" class="form-control" id="inputImagem" name="capa">
				</div>
				
				<div class="form-group">
					<label for="inputTítulo">Título</label>
					<input type="text" class="form-control" id="inputTítulo" name="titulo" value="{{$registro->titulo}}" required>
				</div>
				
				<div class="form-group">
					<label for="inputTexto">Texto</label>
					<textarea name="texto" class="form-control projeto" id="inputTexto" >{{$registro->texto }}</textarea>
				</div>
				

				<button type="submit" title="Alterar" class="btn btn-success">Alterar</button>

				<a href="{{URL::route('painel.projetos.index', array('categoria' => $registro->portfolio_categorias_id))}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>
    
@stop

laravel/app/views/backend/projetos/form.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Adicionar Projeto
        </h2>  

		<form action="{{URL::route('painel.projetos.store')}}" method="post" enctype="multipart/form-data">
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif


				<div class="form-group">
					<label for="inputCategoria">Categoria</label>					 
					<select	name="portfolio_categorias_id" class="form-control" id="inputCategoria" required>
						<option value="">Selecione</option>
						@if(sizeof($categorias))
							@foreach($categorias as $cat)
								<option value="{{$cat->id}}" @if($filtro == $cat->id) selected @endif>{{$cat->titulo}}</option>
							@endforeach
						@endif
					</select>
				</div>

				<div class="form-group">
					<label for="inputImagem">Imagem de Capa</label>
					<input type="file" class="form-control" id="inputImagem" name="capa" required>
				</div>
				
				<div class="form-group">
					<label for="inputTítulo">Título</label>
					<input type="text" class="form-control" id="inputTítulo" name="titulo" @if(Session::has('formulario')) value="{{ $s=Session::get('formulario'); echo $s['titulo'] }}" @endif required>
				</div>
				
				<div class="form-group">
					<label for="inputTexto">Texto</label>
					<textarea name="texto" class="form-control projeto" id="inputTexto" >@if(Session::has('formulario')) {{ $s=Session::get('formulario'); echo $s['texto'] }} @endif</textarea>
				</div>
				

				<button type="submit" title="Inserir" class="btn btn-success">Inserir</button>

				<a href="{{URL::route('painel.projetos.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>
    
@stop

laravel/app/views/backend/projetos/index.blade.php
@section('conteudo')

<div class="container">

    @if(Session::has('sucesso'))
        <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
    @endif

    @if($errors->any())
        <div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
    @endif

    <h2>
        Projetos <a href='{{ URL::route('painel.projetos.create', array('categoria' => $filtro)) }}' class='btn btn-success btn-sm pull-right'><span class='glyphicon glyphicon-plus-sign'></span> Adicionar Projeto</a>
    </h2>

    @if(sizeof($categorias))
    	<div class="btn-group">
	    	@foreach($categorias as $cat)
				<a href="{{URL::route('painel.projetos.index', array('categoria' => $cat->id))}}" title="{{$cat->titulo}}" class="btn btn-sm btn-default @if($cat->id == $filtro) btn-warning @endif">{{$cat->titulo}}</a>
	    	@endforeach
    	</div>
    @endif

    <table class='table table-striped table-bordered table-hover table-sortable' data-tabela='portfolio_projetos'>

        <thead>
            <tr>
                <th>Ordenar</th>
				<th>Título</th>
				<th>Texto</th>
				<th>Imagens</th>
                <th><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($registros as $registro)

            <tr class="tr-row" id="row_{{ $registro->id }}">
                <td class='move-actions'><a href='#' class='btn btn-info btn-move btn-sm'>mover</a></td>
				<td>{{ $registro->titulo }}</td>
				<td>{{ Str::words(strip_tags($registro->texto), 15) }}</td>
				<td><a href="{{URL::route('painel.projetoimagens.index', array('projeto' => $registro->id)) }}" title="gerenciar imagens do projeto" class="btn btn-sm btn-default"><span class="glyphicon glyphicon-picture"></span> gerenciar imagens</a></td>
                <td class="crud-actions">
                    <a href='{{ URL::route('painel.projetos.edit', $registro->id ) }}' class='btn btn-primary btn-sm'>editar</a>
					{{ Form::open(array('route' => array('painel.projetos.destroy', $registro->id), 'method' => 'delete')) }}
						<button type='submit' class='btn btn-danger btn-sm btn-delete'>excluir</button>
					{{ Form::close() }}                    
                </td>
            </tr>

        @endforeach
        </tbody>

    </table>

    
</div>

@stop